### ISSUE TITLE
Initial image size

### ISSUE THREAD

**Issue by achaiah** [Hsuxu/carvana-pytorch-uNet#1]
Hi,

Could you tell me what initial image size you are feeding into your uNet?

Thanks

**Comment by Hsuxu** [comment]
image size is fixed as 1918x1280 or 1024x684, keep the aspect

**Comment by achaiah** [comment]
Great, will try that. Thanks!

**Comment by achaiah** [comment]
Hi,

I tried 1024x684 but I get: `RuntimeError: inconsistent tensor sizes at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/THC/generic/THCTensorMath.cu:141`  Any ideas on what I should check for to make sure the network can accept this size?

Thanks

**Comment by achaiah** [comment]
To clarify, the problem seems to be this line:
`up1 = self.act(self.bn1(self.conv1(torch.cat([self.db1(self.up1(down5)), down4], dim=1))))`

It looks like with input of 1024x684 the dimensions of `self.up1(down5)` are `[2, 96, 64, 44]` while `down4` dimensions are `[2, 96, 64, 43]` so that `torch.cat([self.db1(self.up1(down5)), down4], dim=1)` operation fails.

Any idea on how to fix this?

Thanks
